name: Get Changed Files

on:
  pull_request:
    branches: [ main ]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      
      - name: Display Changed Files
        run: |
          echo "Changed files:"
          for file in $(git diff --name-only --diff-filter=MA ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}); do
            echo "- $file"
          done