name: Get Changed Files

on:
  pull_request:
    branches: [ main ]

jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      
      - name: Display Changed Files
        run: |
          # Convert 10MB to bytes
          threshold=$((10 * 1024 * 1024))
          declare -a output_array
          echo "checking files:"
          for file in $(git diff --name-only --diff-filter=MA ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}); do
            echo "- $file"
            # Get file size in bytes
            size=$(stat -c %s $file)
            
            # Check if the file is larger than 10MB
            if (( size > threshold )); then
                output_array+=("$file")
            fi
          done
          echo 'xxx'
          for file in output_array; do
            echo "- $file"
          done