name: test action
on:
    pull_request:
      branches: [main]
      types: [synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: cat README.md