name: test action
on:
    pull_request:
      branches: [main]
      types: [synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: generate output
        run: echo 'Hello, world!' >> output.txt
      - name: Comment PR with Output
        uses: thollander/actions-comment-pull-request@v2
        with:
            filePath: ./output.txt