name: Customizable Message Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Custom message to display'
        required: true
        type: string

jobs:
  print-custom-message:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Msg: ${{ inputs.message }}"